export const SET_USERS_CONTACTS = 'SET_USERS_CONTACTS';
export const DELETE_USER_CONTACT = 'DELETE_USER_CONTACT';
export const ADD_USER_CONTACT='ADD_USER_CONTACT';
export const SEARCH_CONTACT_USER='SEARCH_CONTACT_USER';

